function f = EOMwControl(mu,u1,u2,u3,x,xdot,y,ydot,z,zdot)
%EOMwControl
%    F = EOMwControl(MU,U1,U2,U3,X,XDOT,Y,YDOT,Z,ZDOT)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Apr-2023 16:09:59

t2 = abs(x);
t3 = abs(y);
t4 = abs(z);
t5 = t2.^2;
t6 = t3.^2;
t7 = t4.^2;
t8 = t5+t6+t7;
t9 = 1.0./t8.^(3.0./2.0);
f = [xdot;ydot;zdot;u1-mu.*t9.*x;u2-mu.*t9.*y;u3-mu.*t9.*z];
