function lambda_dot = lambdaDot(Q1,Q2,Q3,Q4,Q5,Q6,d0,gamma,lambda1,lambda2,lambda3,lambda4,lambda5,lambda6,mu,r_debris1,r_debris2,r_debris3,rho,x,x_ref,xdot,xdot_ref,y,y_ref,ydot,ydot_ref,z,z_ref,zdot,zdot_ref)
%lambdaDot
%    LAMBDA_DOT = lambdaDot(Q1,Q2,Q3,Q4,Q5,Q6,D0,GAMMA,LAMBDA1,LAMBDA2,LAMBDA3,LAMBDA4,LAMBDA5,LAMBDA6,MU,R_DEBRIS1,R_DEBRIS2,R_DEBRIS3,RHO,X,X_REF,XDOT,XDOT_REF,Y,Y_REF,YDOT,YDOT_REF,Z,Z_REF,ZDOT,ZDOT_REF)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Apr-2023 16:09:59

t2 = abs(x);
t3 = abs(y);
t4 = abs(z);
t5 = sign(x);
t6 = sign(y);
t7 = sign(z);
t11 = 1.0./rho;
t12 = -x;
t13 = -y;
t14 = -z;
t8 = t2.^2;
t9 = t3.^2;
t10 = t4.^2;
t15 = r_debris1+t12;
t16 = r_debris2+t13;
t17 = r_debris3+t14;
t18 = abs(t15);
t19 = abs(t16);
t20 = abs(t17);
t24 = t8+t9+t10;
t21 = t18.^2;
t22 = t19.^2;
t23 = t20.^2;
t25 = 1.0./t24.^(3.0./2.0);
t26 = 1.0./t24.^(5.0./2.0);
t27 = t21+t22+t23;
t28 = sqrt(t27);
t29 = 1.0./t28;
t30 = -t28;
t31 = d0+t30;
t32 = t11.*t31;
t33 = tanh(t32);
t34 = t33.^2;
t35 = t34-1.0;
mt1 = [Q1.*(x.*2.0-x_ref.*2.0).*(-1.0./2.0)+lambda4.*mu.*t25-lambda4.*mu.*t2.*t5.*t26.*x.*3.0-lambda5.*mu.*t2.*t5.*t26.*y.*3.0-lambda6.*mu.*t2.*t5.*t26.*z.*3.0+(gamma.*t11.*t18.*t29.*t35.*sign(t15))./2.0;Q2.*(y.*2.0-y_ref.*2.0).*(-1.0./2.0)+lambda5.*mu.*t25-lambda4.*mu.*t3.*t6.*t26.*x.*3.0-lambda5.*mu.*t3.*t6.*t26.*y.*3.0-lambda6.*mu.*t3.*t6.*t26.*z.*3.0+(gamma.*t11.*t19.*t29.*t35.*sign(t16))./2.0;Q3.*(z.*2.0-z_ref.*2.0).*(-1.0./2.0)+lambda6.*mu.*t25-lambda4.*mu.*t4.*t7.*t26.*x.*3.0-lambda5.*mu.*t4.*t7.*t26.*y.*3.0-lambda6.*mu.*t4.*t7.*t26.*z.*3.0+(gamma.*t11.*t20.*t29.*t35.*sign(t17))./2.0;-lambda1-(Q4.*(xdot.*2.0-xdot_ref.*2.0))./2.0];
mt2 = [-lambda2-(Q5.*(ydot.*2.0-ydot_ref.*2.0))./2.0;-lambda3-(Q6.*(zdot.*2.0-zdot_ref.*2.0))./2.0];
lambda_dot = [mt1;mt2];
