function u_star = u_star(R1,R2,R3,lambda4,lambda5,lambda6)
%U_STAR
%    U_STAR = U_STAR(R1,R2,R3,LAMBDA4,LAMBDA5,LAMBDA6)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Apr-2023 16:10:00

u_star = [-lambda4./R1;-lambda5./R2;-lambda6./R3];
